language: node_js
node_js:
  - 16
os:
  - linux
  # - osx
  # - windows

dist: xenial

install: npm install
# install: skip

# script:
#   - npm test
#   - npm run build

# deploy:
#   skip-cleanup: true

# jobs:
#   include:
#     - stage: test
#       script: npm test
#     - # stage name not required, will continue to use `test`
#       script: npm run build
#     - stage: deploy
#       script: ./deploy
# deploy:
#   provider: pages:git
#   token: <encrypted token>
#   edge: true

jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: '$GITHUB_OAUTH_TOKEN'
        skip_cleanup: true
        on:
          tags: true
