language: node_js
node_js:
  - 16
os:
  - linux
  - osx
  - windows

dist: xenial

install: npm install
# install: skip

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
# deploy:
#   provider: pages:git
#   token: <encrypted token>
#   edge: true
# https://config.travis-ci.com/explore
