language: node_js
node_js:
  - 16
os:
  - linux
  - osx
  - windows

dist: xenial

install: npm install
# install: skip

# script:
#   - npm test
#   - npm run build

# deploy:
#   skip-cleanup: true

jobs:
  include:
    - stage: test
      script: npm test
    - # stage name not required, will continue to use `test`
      script: npm run build
    - stage: deploy
      script: ./deploy
# deploy:
#   provider: pages:git
#   token: <encrypted token>
#   edge: true

